"""Runtime hotfixes for Phase 6.5 backtests.

This keeps the experiment moving without changing the model architecture.  The
Phase 6.5 contrarian factor code uses threshold column names generated by
`keys()` (e.g. `short_hit_2p5`), while an earlier implementation referenced
`short_hit_025`.  Patch the function at interpreter startup so historical runs
remain reproducible while the source module is corrected in the next cleanup.
"""

try:
    from src import moe_engine_phase65 as _m
    import numpy as _np
    import pandas as _pd

    def _fixed_train_contrarian_factors(train_df, experts):
        work = _m.add_cpr_features(train_df.copy())
        work = _m.add_bidirectional_targets(work, 0.0125, _m.THRESHOLDS)
        work["regime_code"] = _m.regime_labels(work)
        hkeys = _m.keys(_m.THRESHOLDS)
        long_hit_col = f"long_hit_{hkeys[0]}"
        short_hit_col = f"short_hit_{hkeys[0]}"
        out = {}
        for regime in sorted(_pd.Series(work.regime_code).dropna().astype(int).unique()):
            sub = work[work.regime_code.astype(int) == int(regime)].copy()
            long_cons = _pd.Series(0.0, index=sub.index)
            short_cons = _pd.Series(0.0, index=sub.index)
            for name in experts:
                raw = _m._rule_signal(sub, name)
                long_cons = long_cons + raw.groupby(sub.date).rank(pct=True)
                short_cons = short_cons + (-raw).groupby(sub.date).rank(pct=True)
            n = max(len(experts), 1)
            long_cons = long_cons / n
            short_cons = short_cons / n
            strong_long = sub.loc[long_cons >= 0.75]
            strong_short = sub.loc[short_cons >= 0.75]
            reverse_short = (
                float(strong_long[short_hit_col].mean()
                      * strong_long.short_mfe.clip(0, 0.10).mean() / 0.025)
                if not strong_long.empty else 0.0
            )
            reverse_long = (
                float(strong_short[long_hit_col].mean()
                      * strong_short.long_mfe.clip(0, 0.10).mean() / 0.025)
                if not strong_short.empty else 0.0
            )
            out[int(regime)] = {
                "short_from_long": float(_np.clip(reverse_short, 0.0, 0.60)),
                "long_from_short": float(_np.clip(reverse_long, 0.0, 0.60)),
            }
        return out

    _m.train_contrarian_factors = _fixed_train_contrarian_factors
except Exception:
    # Never prevent unrelated Python processes from starting.
    pass
